version: "{build}"
build: false
environment:
    matrix:
        - PYTHON: "C:/Python27"
        - PYTHON: "C:/Python34"

init:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    - ECHO "Updating Environment"
    - python -m pip install -U setuptools
    - python -m pip install -U pip
    - python -m pip install -U wheel
    
install:
    - python -m pip install .
    - python -m pip install -r requirements-optional.txt

    # Check that we have the expected version and architecture for Python
    - python -c "import sys, os;sys.stdout.write(str(sys.version) + os.linesep)"
    - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
    - python -m pip list
      
test_script:
    - "%PYTHON%/Scripts/green.exe -vvv green"

platform:
    - AnyCPU
